[package]
name = "standing"
version = "0.1.0"
authors = ["Keith Wansbrough <Keith.Wansbrough@metaswitch.com>"]

[dependencies]
gfx = "0.16"
gfx_window_glutin = "0.16"
glutin = "0.8"
time = "0.1"
cgmath = "0.14"
config = { version = "0.4", features = ["yaml"] }
